name: pokemons_repository
description: Flutter package that handles pokemon related requests
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pokemons_api:
    path: ../pokemons_api

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.22.0
  very_good_analysis: ^3.0.0
